name: parchment
description: Platform-agnostic rich text document model based on Delta format and used in Fleather editor.
version: 1.22.0
homepage: https://fleather-editor.github.io
repository: https://github.com/fleather-editor/fleather
issue_tracker: https://github.com/fleather-editor/fleather/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  parchment_delta: ^1.0.0
  html: ^0.15.5
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1
