name: parchment
description: Platform-agnostic rich text document model based on Delta format and used in Fleather editor.
version: 1.14.0
homepage: https://fleather-editor.github.io
repository: https://github.com/fleather-editor/fleather
issue_tracker: https://github.com/fleather-editor/fleather/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  parchment_delta: ^1.0.0
  quiver: ^3.1.0
  html: ^0.15.1

dev_dependencies:
  test: ^1.21.3
  lints: ^3.0.0
