name: fleather
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.18.0
homepage: https://fleather-editor.github.io
repository: https://github.com/fleather-editor/fleather
issue_tracker: https://github.com/fleather-editor/fleather/issues
documentation: https://fleather-editor.github.io/docs/getting-started/quick-start/
screenshots:
  - description: "Fleather demo"
    path: images/screenshot.png
topics:
  - editor
  - text
  - wysiwyg
  - rich-text-editor
  - widgets

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  parchment_delta: ^1.0.0
  parchment: ^1.18.0
  intl: ^0.19.0

dependency_overrides:
  parchment:
    path: ../parchment

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.0
  meta: ^1.10.0
