name: fleather
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0
homepage: https://github.com/fleather-editor/fleather

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  quill_delta: ^3.0.0-nullsafety.2
  parchment: ^1.0.0
  characters: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
