name: fleather
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.26.0
homepage: https://fleather-editor.github.io
repository: https://github.com/fleather-editor/fleather
issue_tracker: https://github.com/fleather-editor/fleather/issues
documentation: https://fleather-editor.github.io/docs/getting-started/quick-start/
screenshots:
  - description: "Fleather demo"
    path: images/screenshot.png
topics:
  - editor
  - text
  - wysiwyg
  - rich-text-editor
  - widgets

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  parchment_delta: ^1.0.0
  parchment: ^1.25.1
  intl: ">=0.19.0 <0.21.0"

dependency_overrides:
  parchment:
    path: ../parchment

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3
  mocktail: ^1.0.4
  meta: ^1.17.0

flutter:
  generate: true
